### ISSUE TITLE
Info: Assigning country "Denmark" and store "Irma" to some of the existing products.

### ISSUE THREAD

**Issue by saihtaM** [openfoodfacts/outside-data#1]
This is just a short info about when in the future people wonder why Denmark and Irma is on many of the products.

At the time of writing, dk.openfoodfacts.org does only have 166 products, which is not much.

So I've sent a few mails around to different stores, asking if I could get a list of barcodes that they have in stock. 
The first one to respond was Mette from Irma, she released a list of 4871 (incl. shortcodes) that we could use to find existing products on OFF. 

So what we're doing with the data, is adding "Denmark" and "Irma" to the existing products we find. 

Thanks to Irma for being awesome!

**Comment by stephanegigandet** [comment]
Thank you Mathias, I ran a bot to add Denmark and Irma to the existing products. We now have 297 products on http://dk.openfoodfacts.org/

82 products have been changed: http://dk.openfoodfacts.org/informer/mathias/store/irma-dk
